# Change these first
owner: psharma04 # Your GitHub organization or username, where this repository lives
repo: discord-bot-monitor # The name of this repository

sites:
  - name: Main Bot Server (🇦🇺)
    url: $MAIN_SERVER
    icon: https://cdn.statically.io/img/raw.githubusercontent.com/f=auto/psharma04/image-repo/main/uploads/robot_1f916.png
  - name: Music Server (🇫🇷)
    check: "tcp-ping"
    url: $MUSIC_SERVER
    port: 2333
    icon: https://cdn.statically.io/img/raw.githubusercontent.com/f=auto/psharma04/image-repo/main/uploads/musical-note_1f3b5.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: discord.pshar.ma
  theme: ocean
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PepsiBot
  introTitle: "**PepsiBot** is an all-purpose Discord bot run by Pranav Sharma."
  introMessage: The bot is based on Discord Red, a NodeJS project for building Discord bots. [Add it to your server today!](https://discord.com/oauth2/authorize?client_id=887925551346642965&scope=bot)
  scripts:
    - src: https://arc.io/widget.min.js#6x6hfFsy
      async: true
  navbar:
    - title: Status
      href: /
      - title: Docs
      href: https://docs.discord.pshar.ma/
    - title: Donate
      href: https://ko-fi.com/hyperbolicpurple
    - title: About the Dev
      href: https://blog.pshar.ma
    - title: Invite the Bot!!
      href: https://discord.com/oauth2/authorize?client_id=887925551346642965&scope=bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
